baseURL = ""
languageCode = "en-us"
title = "Mitchell Friedman"
theme = "kube"
description = "Mitchell Friedman"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Mitchell Friedman"
  github = "mitchfriedman"
  twitter = "mitchfriedman5" 
  email = "mitchfriedman5@gmail.com"

[[menu.main]]
    name = "Home"
    weight = -1000
    url = "/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
